# ==========================================
# APPLICATION
# ==========================================

spring.application.name=iwms-backend

server.port=8081


# ==========================================
# POSTGRESQL DATABASE
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/iwms_db
spring.datasource.username=postgres
spring.datasource.password=shivi28


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
